apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    control-plane: controller-manager
  name: harbor-cluster-operator-controller-manager-metrics-service
  namespace: kube-repo
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-cluster-operator-webhook-service
  namespace: kube-repo
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    control-plane: controller-manager
  name: harbor-operator-controller-manager-metrics-service
  namespace: kube-repo
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-operator-webhook-service
  namespace: kube-repo
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    name: kube-repo
  name: operator
  namespace: kube-repo
spec:
  ports:
    - name: http
      port: 4222
    - name: https
      port: 4233
  selector:
    name: kube-repo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: postgres-operator
  namespace: kube-repo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: postgres-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    control-plane: controller-manager
  name: harbor-cluster-operator-controller-manager
  namespace: kube-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        goharbor.io/cluster-version: 0.5.0
        goharbor.io/template-engine: Kustomization
        goharbor.io/template-version: 2020915-1140
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          image: goharbor/harbor-cluster-operator:latest
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    control-plane: controller-manager
  name: harbor-operator-controller-manager
  namespace: kube-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        goharbor.io/cluster-version: 0.5.0
        goharbor.io/template-engine: Kustomization
        goharbor.io/template-version: 2020915-1140
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          env:
            - name: CONFIGURATION_FROM
              value: 'env:'
          envFrom:
            - configMapRef:
                name: harbor-operator-operator-config-6g2hb7ttdf
                optional: true
          image: goharbor/harbor-operator:latest
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 200Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: kube-repo
  namespace: kube-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-repo
  template:
    metadata:
      annotations:
        goharbor.io/cluster-version: 0.5.0
        goharbor.io/template-engine: Kustomization
        goharbor.io/template-version: 2020915-1140
      labels:
        name: kube-repo
    spec:
      containers:
        - image: minio/k8s-operator:v3.0.13
          imagePullPolicy: IfNotPresent
          name: kube-repo
          resources:
            requests:
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      serviceAccountName: kube-repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: postgres-operator
  namespace: kube-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      annotations:
        goharbor.io/cluster-version: 0.5.0
        goharbor.io/template-engine: Kustomization
        goharbor.io/template-version: 2020915-1140
      labels:
        name: postgres-operator
    spec:
      containers:
        - env:
            - name: CONFIG_MAP_NAME
              value: postgres-operator
          image: registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
          imagePullPolicy: IfNotPresent
          name: postgres-operator
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      serviceAccountName: postgres-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  labels:
    app: redisoperator
  name: redisoperator
  namespace: kube-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        goharbor.io/cluster-version: 0.5.0
        goharbor.io/template-engine: Kustomization
        goharbor.io/template-version: 2020915-1140
      labels:
        app: redisoperator
    spec:
      containers:
        - image: quay.io/spotahome/redis-operator:latest
          imagePullPolicy: IfNotPresent
          name: app
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      restartPolicy: Always
      serviceAccountName: redisoperator
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-cluster-operator-serving-cert
  namespace: kube-repo
spec:
  dnsNames:
    - harbor-cluster-operator-webhook-service.kube-repo.svc
    - harbor-cluster-operator-webhook-service.kube-repo.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  annotations:
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-operator-serving-cert
  namespace: kube-repo
spec:
  dnsNames:
    - harbor-operator-webhook-service.kube-repo.svc
    - harbor-operator-webhook-service.kube-repo.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-repo/harbor-cluster-operator-serving-cert
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-cluster-operator-mutating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: harbor-cluster-operator-webhook-service
        namespace: kube-repo
        path: /mutate-goharbor-io-v1alpha1-harborcluster
    failurePolicy: Fail
    name: mharborcluster.kb.io
    rules:
      - apiGroups:
          - goharbor.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - harborclusters
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-repo/harbor-operator-serving-cert
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-operator-mutating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: harbor-operator-webhook-service
        namespace: kube-repo
        path: /mutate-goharbor-io-v1alpha1-harbor
    failurePolicy: Fail
    name: mharbor.kb.io
    rules:
      - apiGroups:
          - goharbor.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - harbors
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-repo/harbor-cluster-operator-serving-cert
    goharbor.io/cluster-version: 0.5.0
    goharbor.io/template-engine: Kustomization
    goharbor.io/template-version: 2020915-1140
  name: harbor-cluster-operator-validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: harbor-cluster-operator-webhook-service
        namespace: kube-repo
        path: /validate-goharbor-io-v1alpha1-harborcluster
    failurePolicy: Fail
    name: vharborcluster.kb.io
    rules:
      - apiGroups:
          - goharbor.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - harborclusters