---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/deploy-engine: Kustomization
    goharbor.io/deploy-mode: harbor
    goharbor.io/operator-version: v1.0.0
  labels:
    control-plane: harbor-operator
  name: harbor-operator
  namespace: kube-repo
spec:
  selector:
    matchLabels:
      control-plane: harbor-operator
  template:
    metadata:
      annotations:
        goharbor.io/deploy-engine: Kustomization
        goharbor.io/deploy-mode: harbor
        goharbor.io/operator-version: v1.0.0
      labels:
        control-plane: harbor-operator
    spec:
      containers:
        - args:
            - --enable-leader-election
            - --metrics-addr=127.0.0.1:8080
          command:
            - /manager
          env:
            - name: CORE_DOCKER_IMAGE
              value: quay.io/goharbor/harbor-core:v2.1.2
            - name: JOBSERVICE_DOCKER_IMAGE
              value: quay.io/goharbor/harbor-jobservice:v2.1.2
            - name: PORTAL_DOCKER_IMAGE
              value: quay.io/goharbor/harbor-portal:v2.1.2
            - name: REGISTRYCTL_DOCKER_IMAGE
              value: quay.io/goharbor/harbor-registryctl:v2.1.2
            - name: REGISTRY_DOCKER_IMAGE
              value: quay.io/goharbor/registry-photon:v2.1.2
            - name: CHARTMUSEUM_DOCKER_IMAGE
              value: quay.io/goharbor/chartmuseum-photon:v2.1.2
            - name: NOTARYSERVER_DOCKER_IMAGE
              value: quay.io/goharbor/notary-server-photon:v2.1.2
            - name: NOTARYSIGNER_DOCKER_IMAGE
              value: quay.io/goharbor/notary-signer-photon:v2.1.2
            - name: TRIVY_DOCKER_IMAGE
              value: quay.io/goharbor/trivy-adapter-photon:v2.1.2
            - name: HARBORCLUSTER_STORAGE_IMAGE
              value: quay.io/goharbor/minio:RELEASE.2020-08-13T02-39-50Z
            - name: HARBORCLUSTER_CACHE_IMAGE
              value: quay.io/goharbor/redis:5.0-alpine
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: goharbor/harbor-operator:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: ready
            initialDelaySeconds: 2
            periodSeconds: 2
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 5000
              name: ready
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: ready
            initialDelaySeconds: 2
            periodSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /etc/harbor-operator/templates
              name: configuration-templates
              readOnly: true
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - configMap:
            name: config-template
          name: configuration-templates
---
