apiVersion: v1
kind: ConfigMap
metadata:
  namespace: clt-devops
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 20.0.2.10 - 20.0.2.200