---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-repo
  name: harbor-redis-config
data:
  redis-config:  |
    maxmemory 20mb
    maxmemory-policy allkeys-lr
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-repo
  name: harbor-redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-repo
  name: harbor-redis
  labels:
    app: redis
spec:
  containers:
    - name: harbor-redis
      image: redis:latest
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: harbor-redis-config
        items:
          - key: redis-config
            path: redis.conf